version: "3.3"
services:
  user-db:
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$USERDB_MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$USERDB_MYSQL_DATABASE
      - MYSQL_USER=$USERDB_MYSQL_USER
      - MYSQL_PASSWORD=$USERDB_MYSQL_PASSWORD
      - MYSQL_DATABASE=$USERDB_MYSQL_DATABASE
      - USERDB_MYSQL_LOCAL_PORT=$USERDB_MYSQL_LOCAL_PORT
      - USERDB_MYSQL_DOCKER_PORT=$USERDB_MYSQL_DOCKER_PORT
    ports:
      - $USERDB_MYSQL_LOCAL_PORT:$USERDB_MYSQL_DOCKER_PORT
    volumes:
      - user_data:/var/lib/mysql
      # - ./sqldata/student_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  student-db:
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_LOCAL_PORT=$MYSQL_LOCAL_PORT
      - MYSQL_DOCKER_PORT=$MYSQL_DOCKER_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - student_llm_chat_data:/var/lib/mysql
      - ./sqldata/student_data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  chat-api:
    build: ./chat-api
    restart: on-failure
    command: npm run start
    env_file:
      - .env
    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - MYSQL_HOST=student-db
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_NAME=$MYSQL_DATABASE
      - MYSQL_DOCKER_PORT=$MYSQL_DOCKER_PORT
      - MYSQL_LOCAL_PORT=$MYSQL_LOCAL_PORT
    depends_on:
      student-db:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ./chat-api:/app
      - /app/node_modules

  chat-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    command: npm run dev
    env_file:
      - .env
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    environment:
      - AUTH_SECRET=$AUTH_SECRET
      - BACKEND_ENTRYPOINT=$BACKEND_ENTRYPOINT
      - NODE_PORT=$NODE_PORT
      - USERDB_URL=mysql://root:$USERDB_MYSQL_ROOT_PASSWORD@user-db:$USERDB_MYSQL_DOCKER_PORT/$USERDB_MYSQL_DATABASE
    stdin_open: true
    depends_on:
      user-db:
        condition: service_healthy
      chat-api:
        condition: service_started
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  student_llm_chat_data:
  user_data:
  # auth_data:
