version: "3.3"
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_LOCAL_PORT=$MYSQL_LOCAL_PORT
      - MYSQL_DOCKER_PORT=$MYSQL_DOCKER_PORT
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - student_llm_chat_data:/var/lib/mysql

  chat-api:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_NAME=$MYSQL_DATABASE
      - MYSQL_DOCKER_PORT=$MYSQL_DOCKER_PORT
      - MYSQL_LOCAL_PORT=$MYSQL_LOCAL_PORT
    depends_on:
      - db
    stdin_open: true
    tty: true


volumes:
  student_llm_chat_data:
