name: CI Check

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      need_build_result:
        required: false
        type: boolean
        default: false
  pull_request:
    branches: ["main"]

jobs:
  typecheck-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check typecheck on client
        run: |
          cd client
          npm run typecheck

  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check lint on client
        run: |
          cd client
          npm run lint -- --max-warnings 0

  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check build on client
        run: |
          cd client
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-result
          path: out/
        if: ${{ inputs.need_build_result }}

  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check build on api
        run: |
          cd chat-api
          npm run start

      - uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-result
          path: out/
        if: ${{ inputs.need_build_result }}
