name: Docker Compose CI (Manual)

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 
  workflow_dispatch:  

env:
  MYSQL_DATABASE: chatdb
  MYSQL_LOCAL_PORT: 3307
  MYSQL_DOCKER_PORT: 3306
  NODE_PORT: 5005
  MYSQL_USER: chatuser
  CLIENT_PORT: 3000
  USERDB_MYSQL_DATABASE: userdb
  USERDB_MYSQL_LOCAL_PORT: 3307
  USERDB_MYSQL_DOCKER_PORT: 3307
  USERDB_MYSQL_USER: userdbuser
  BACKEND_ENTRYPOINT: http://localhost
  CORS_ORIGIN: http://localhost:3000

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check that .env File does not exist yet
        run: |
          if [ -f .env ]; then
            echo "❌ ERROR: .env file found!"
            exit 1
          fi
          echo "✅ .env file not found. Proceeding..."

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Create Temporary .env File
        run: |
          echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> .env
          echo "MYSQL_LOCAL_PORT=${MYSQL_LOCAL_PORT}" >> .env
          echo "MYSQL_DOCKER_PORT=${MYSQL_DOCKER_PORT}" >> .env
          echo "NODE_PORT=${NODE_PORT}" >> .env
          echo "MYSQL_USER=${MYSQL_USER}" >> .env
          echo "CLIENT_PORT=${CLIENT_PORT}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "USERDB_MYSQL_DATABASE=${USERDB_MYSQL_DATABASE}" >> .env
          echo "USERDB_MYSQL_LOCAL_PORT=${USERDB_MYSQL_LOCAL_PORT}" >> .env
          echo "USERDB_MYSQL_DOCKER_PORT=${USERDB_MYSQL_DOCKER_PORT}" >> .env
          echo "USERDB_MYSQL_USER=${USERDB_MYSQL_USER}" >> .env
          echo "USERDB_MYSQL_ROOT_PASSWORD=${{ secrets.USERDB_MYSQL_ROOT_PASSWORD }}" >> .env
          echo "USERDB_MYSQL_PASSWORD=${{ secrets.USERDB_MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "BACKEND_ENTRYPOINT=${BACKEND_ENTRYPOINT}" >> .env
          echo "CORS_ORIGIN=${CORS_ORIGIN}" >> .env
          echo "✅ .env file created."
        

      - name: Build and Start Services
        run: docker-compose --env-file .env up -d --build

      - name: Show Running Containers
        run: docker ps

      - name: Stop Services
        run: docker-compose down
